# Site-wide settings
# ------------------
#
title: RECOMB 2026
iteration: "30th"
location: "Thessaloniki, Greece"
city: "Thessaloniki"
country: "Greece"

#
author:
   name: RECOMB Conference
   email: info@recombconf.org
#
# The `>` after `description:` means to ignore line-breaks until next key. If
#   you wish to omit the line-break after the end of text, use `>-` instead.
# description: >
#   Write an awesome description for your new site here. You can edit this line
#   in _config.yml. It will appear in your document head meta (for Google search
#   results) and in your feed.xml site description.


# Build settings
# --------------
#
# If you wish to use the gem-version of Minima with or without a Gemfile, use
#   the following setting:
# theme: minima
#
# **OR** if you wish to use the theme directly from the GitHub repository by
#   bypassing a Gemfile, use the following setting instead.
#   It is best that you lock to a particular commit and update if uptream changes
#   do not affect your site adversely.
# remote_theme: jekyll/minima@d4d779a
#
# Minima requires the following plugins:
#plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
#
# Uncomment the following setting if you wish to disable deprecation warnings
#   from newer versions of sass converter. Adapt as required.
# sass:
#   quiet_deps: true
#   silence_deprecations: [import]


# Minima-specific settings (applicable to Minima v3 and above only)
# -----------------------------------------------------------------
#
#  *All described config keys below should be nested under the top-level
#   `minima` key.*
#
minima:
#   Minima skin selection. Available skins are:
#     * classic            Default, light color scheme.
#     * dark               Dark variant of the classic skin.
#     * auto               Adaptive skin based on the classic and dark skins.
#     * solarized-light    Light variant of solarized color scheme.
#     * solarized-dark     Dark variant of solarized color scheme.
#     * solarized          Adaptive skin for solarized color scheme skins.
  skin: auto

#   Social Media Links.
#     Renders icons via Font Awesome Free webfonts CDN, based on ordered list of
#     entries. Valid entry keys:
#       * title    Tooltip rendered on hovering over icon.
#       * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
#       * url      Full URL of social profile.
social_links:
    - title: Email 
      icon: envelope
      url: "mailto:info@recombconf.org"
    - title: RECOMB at X 
      icon: x-twitter
      url: "https://x.com/RECOMBconf"
    - title: RECOMB at BlueSky 
      icon: bluesky
      url: "https://bsky.app/profile/recombconf.bsky.social"
#
#   Hide syndication feed subscription link.
#     RSS / Atom feed link is always rendered as the last item of social-links
#     list. Set below key to `true` to not have the link to feed rendered as
#     part of social-links list.

hide_site_feed_link: true

main_navigation:
  - title: Home
    url: /index
  - title: Conference
    children:
      - title: Committees
        url: /committees
      - title: Key dates & Deadlines
        url: /keydates_and_deadlines
      - title: Call for Papers
        url: /call_for_papers
      - title: Call for Abstracts
        url: /call_for_abstracts
      - title: Call for Highlights
        url: /call_for_highlights
  - title: Register
    children:
      - title: RECOMB and Satellites
        url: /register
      - title: Travel Fellowships
        url: /travel_fellowships
  - title: Program
    children:
      - title: Program Schedule
        url: /program
      - title: Keynotes
        url: /keynotes
      - title: Poster Guidelines
        url: /posters
  - title: Venue
    children:
      - title: Main Conference Venue
        url: /venue_main
      - title: Satellites Venue
        url: /venue_satellites
      - title: Hotels
        url: /hotels
      - title: Airport Directions
        url: /airport
      - title: Things to do in Thessaloniki
        url: /things_to_do
      - title: Local Transportation
        url: /transportation
      - title: Visa Information
        url: /visa
  - title: Satellites
    children:
      - title: RECOMB-Seq
        url: https://recomb-seq.github.io/
        external: true # Mark as external link
      - title: RECOMB-CCB
        url: https://recomb.org/recomb-ccb2026
        external: true
      - title: RECOMB-CG
        url: https://recomb-cg.org/
        external: true
      - title: RECOMB-Arch
        url: https://recomb-arch.github.io/
        external: true # Mark as external link
      - title: RECOMB-Genetics
        url: /recombgenetics
  - title: Sponsors
    children:
      - title: RECOMB Sponsors
        url: /sponsors
      - title: Sponsorship Packages
        url: /sponsorship_packages

#  Removed since it overflows - and the link is moved to the logo instead
#  - title: About RECOMB
#    url: https://www.recomb.org
#    external: true

# Custom variables
deadlines:
  abstract_submission: "7 November 2025, 23:59 AoE"
  paper_submission: "14 November 2025, 23:59 AoE"
  author_notification: "12 January 2026"
  final_version: "25 February 2026"
  early_registration: "TBA" # placeholder
  late_registration: "TBA" # placeholder
  highlights_submission: "TBA"
  highlights_notification: "TBA"
  highlights_cutoff: "January 1, 2025" # earliest journal pub date for highlights submissions
  poster_submission: "TBA"
  poster_notification: "TBA"
  late_poster_submission: "TBA"
  late_poster_notification: "TBA"
  travel_fellow_application: "TBA"
  travel_fellow_notification: "TBA"
  conference_dates: "26-29 May 2026"
  satellite_dates: "24-25 May 2026" # for the home page
  satellite_seq: "24-25 May 2026"
  satellite_ccb: "24-25 May 2026"
  satellite_cg: "24-25 May 2026"
  satellite_genetics: "25 May 2026"
  satellite_priv: "25 May 2026"
  satellite_arch: "24 May 2026"
  
links: 
  easychair: "https://easychair.org/conferences/?conf=recomb2026"
 

team:
  pc_chair: "Tony Stark"
  pc_chair_email: "tony.stark@recombconf.org"
  pc_chair_institute: "Stark Industries"
  pc_chair_url: "https://tonystark.com"
  highlights_chair: "Bruce Banner"
  highlights_chair_email: "bruce.banner@recombconf.org"
  highlights_chair_institute: "Banner Industries"
  highlights_chair_url: "https://brucebanner.com"
  posters_chair: "Steve Rogers"
  posters_chair_email: "steve.rogers@recombconf.org"
  posters_chair_institute: "Rogers Industries"
  posters_chair_url: "https://steve-rogers.com"
  travel_fellowship_chair: "Natasha Romanoff"
  travel_fellowship_chair_email: "natasha.romanoff@recombconf.org"
  travel_fellowship_chair_institute: "Romanoff Industries"
  travel_fellowship_chair_url: "https://natasharomanoff.com"
  industry_chair: "Thor Odinson"
  industry_chair_email: "thor.odinson@recombconf.org"
  industry_chair_institute: "Odinson Industries"
  industry_chair_url: "https://thorodinson.com"

#  nav_pages:
#     - about.md
#     - committes.md
#     - register.md
#
#   Set to `true` to show excerpts on the homepage.
#   show_excerpts: false
#
#   Minima date format.
#     The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
#     Refer to https://shopify.github.io/liquid/filters/date/ for valid values
#   date_format: "%b-%d-%Y"
#

